Update release.yml

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -51,7 +51,6 @@ jobs:
     runs-on: "ubuntu-22.04"
     outputs:
       val: ${{ steps.plan.outputs.manifest }}
-      # تغییرات در این ۳ خط اعمال شده تا فقط تگ‌های واقعی را بخواند
       tag: ${{ github.ref_type == 'tag' && github.ref_name || '' }}
       tag-flag: ${{ github.ref_type == 'tag' && format('--tag={0}', github.ref_name) || '' }}
       publishing: ${{ github.ref_type == 'tag' }}
@@ -63,6 +62,8 @@ jobs:
           persist-credentials: false
           submodules: recursive
       - name: Install dist
+        # we specify bash to get pipefail; it guards against the `curl` command
+        # failing. otherwise `sh` won't catch that `curl` returned non-0
         shell: bash
         run: "curl --proto '=https' --tlsv1.2 -LsSf https://github.com/axodotdev/cargo-dist/releases/download/v0.30.2/cargo-dist-installer.sh | sh"
       - name: Cache dist
@@ -71,7 +72,6 @@ jobs:
           name: cargo-dist-cache
           path: ~/.cargo/bin/dist
       - id: plan
-        # این خط هم آپدیت شده است
         run: |
           dist ${{ (github.ref_type == 'tag' && format('host --steps=create --tag={0}', github.ref_name)) || 'plan' }} --output-format=json > plan-dist-manifest.json
           echo "dist ran successfully"
@@ -207,6 +207,7 @@ jobs:
           path: |
             ${{ steps.cargo-dist.outputs.paths }}
             ${{ env.BUILD_MANIFEST_NAME }}
+            
   # Determines if we should publish/announce
   host:
     needs:
